import React,{useEffect,useState} from 'react';
import {api} from '../../services/api';
import {useApp} from '../../context/AppContext';
export function RecoveryOperations(){
 const [rows,setRows]=useState<{email:string;name:string;requestedAt:number}[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await api.recoveryRequests();if(r.success)setRows(r.requests);}catch{setNotice('No se pudieron cargar las solicitudes.');}}
 useEffect(()=>{void load();},[]);
 async function prepare(email:string){setBusy(true);try{const r=await api.prepareRecovery(email);setNotice(r.message);if(r.success)await load();}catch{setNotice('No se guardó el código.');}finally{setBusy(false);}}
 return <section className="p-4 border rounded-2xl space-y-3 mb-4"><h2 className="font-bold">Recuperación de acceso</h2><p className="text-sm">En modo manual, prepara el código y envía el mensaje únicamente al correo registrado. El código anterior queda invalidado.</p><button onClick={()=>void load()} className="underline">Actualizar solicitudes</button>{rows.map(r=><div key={r.email} className="flex flex-wrap gap-3 items-center"><span>{r.name} · {r.email}</span><button disabled={busy} onClick={()=>void prepare(r.email)} className="bg-red-600 text-white p-2 rounded-lg">Preparar envío manual</button></div>)}{!rows.length && <p>No hay solicitudes vigentes.</p>}{notice && <textarea readOnly aria-label="Mensaje de recuperación" value={notice} className="w-full border rounded p-3" rows={4}/>}</section>;
}
export function CashCommissionOperations(){
 const {stores,storeBalances,orders,disputes}=useApp();
 const [storeId,setStoreId]=useState(''),[amount,setAmount]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const due=orders.filter(o=>o.storeId===storeId && o.paymentMethod==='CASH_ON_DELIVERY' && o.status==='DELIVERED' && o.paymentStatus==='PAID' && o.settlementStatus==='PENDING' && !o.settlementId && !disputes.some(d=>d.orderId===o.id && ['OPEN','UNDER_REVIEW'].includes(d.status))).reduce((n,o)=>n+Math.max(0,o.plazaCommissionAmount-(o.settlementPaidCommission || 0)),0);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await api.cashCommissionReceipt(storeId,Number(amount),reference);setNotice(r.message);if(r.success){setAmount('');setReference('');}}catch{setNotice('No se pudo confirmar el cobro. Reintenta con la misma referencia.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="border rounded-2xl p-4 space-y-3"><h3 className="font-bold">Cobro de comisiones contra entrega</h3><p className="text-sm">Registra el dinero recibido después de comprobarlo en la cuenta bancaria de Plazado.</p><select required aria-label="Tienda" value={storeId} onChange={e=>setStoreId(e.target.value)} className="border p-2 rounded w-full"><option value="">Selecciona una tienda</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name} · pendiente RD${storeBalances[s.id]?.pendingCashCommissions || 0}</option>)}</select><p>Cobrable sin reclamaciones ni reservas: RD${due.toFixed(2)}</p><input required aria-label="Monto recibido" placeholder="Monto recibido RD$" type="number" min="0.01" max={due} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="border p-2 rounded w-full"/><input required aria-label="Referencia bancaria" minLength={6} maxLength={120} placeholder="Referencia bancaria comprobada" value={reference} onChange={e=>setReference(e.target.value)} className="border p-2 rounded w-full"/><button disabled={busy || due<=0} className="bg-red-600 text-white p-3 rounded-xl disabled:opacity-50">{busy?'Guardando…':'Registrar comisión recibida'}</button>{notice && <p role="status">{notice}</p>}</form>;
}

export function PayPalOperations(){
 const {orders}=useApp();const [id,setId]=useState(''),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const groups=[...new Set(orders.filter(o=>o.paymentMethod==='PAYPAL' && o.paypalPayment?.orderId).map(o=>o.paypalPayment!.orderId))];
 async function run(refund:boolean){setBusy(true);try{const r=refund?await api.refundPayPal(id,reason):await api.reconcilePayPal(id);setNotice(r.message);}catch{setNotice('No se confirmó la operación. Reintenta la misma referencia.');}finally{setBusy(false);}}
 return <section className="border rounded-2xl p-4 space-y-3"><h3 className="font-bold">Conciliación y reembolso PayPal</h3><select aria-label="Compra PayPal" value={id} onChange={e=>setId(e.target.value)} className="border rounded p-2 w-full"><option value="">Selecciona una compra</option>{groups.map(value=><option key={value}>{value}</option>)}</select><button disabled={busy || !id} onClick={()=>void run(false)} className="border rounded p-2">Consultar y conciliar cobro</button><p className="text-sm">El reembolso devuelve el importe completo de esta compra a todas las tiendas incluidas. Los fondos liquidados requieren revisión bancaria. La devolución física se gestiona por separado.</p><input aria-label="Motivo del reembolso" minLength={10} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo documentado del reembolso" className="border rounded p-2 w-full"/><button disabled={busy || !id || reason.trim().length<10} onClick={()=>{if(window.confirm('¿Confirmas devolver el importe completo de esta compra mediante PayPal?'))void run(true);}} className="bg-red-600 text-white rounded p-3 disabled:opacity-50">Reembolsar compra completa</button>{notice && <p role="status">{notice}</p>}</section>;
}
